export const event = [
  {
    slug: "taylor-musuc-fest",
    imagen: "/images/1.jpg",
    nombre: "Taylor Music Fest",
    fecha: "10 Nov. 2024",
    hora: "12:00 am",
    descripcion:
      "Taylor Music Fest es el evento musical más esperado del año, donde podrás disfrutar de una experiencia única e inolvidable. Este festival contará con la presencia de la icónica Taylor Swift, quien ofrecerá un concierto espectacular con sus mayores éxitos y nuevas canciones. Además, la Banda X se unirá al espectáculo, brindando su energía y talento en el escenario. El festival no solo será un deleite musical, sino que también habrá una gran variedad de puestos de comida, actividades interactivas, y áreas de descanso para que puedas disfrutar al máximo de este día lleno de diversión y entretenimiento. ",
    invitados: "Taylor Swift, Banda X",
    costo: "899",
    lugar: "New York",
  },
  {
    slug: "dj-fest-vip",
    imagen: "/images/2.jpg",
    nombre: "DJ's Fest VIP",
    fecha: "15 Nov. 2024",
    hora: "10:00 am",
    descripcion: "Explora las obras más recientes de artistas contemporáneos.",
    invitados: "Artista A, Artista B",
    costo: "50",
    lugar: "San Francisco",
  },
  {
    slug: "taller-nocturno",
    imagen: "/images/3.jpg",
    nombre: "Taller Nocturno",
    fecha: "20 Nov. 2024",
    hora: "7:00 pm",
    descripcion:
      "Aprende técnicas avanzadas para capturar fotos nocturnas impresionantes.",
    invitados: "Fotógrafo C, Fotógrafo D",
    costo: "120",
    lugar: "Los Angeles",
  },
  {
    slug: "international-fest",
    imagen: "/images/4.jpg",
    nombre: "Internacional Fest",
    fecha: "25 Nov. 2024",
    hora: "11:00 am",
    descripcion: "Saborea platillos de diferentes culturas en un solo lugar.",
    invitados: "Chef E, Chef F",
    costo: "30",
    lugar: "Chicago",
  },
  {
    slug: "festival-5k",
    imagen: "/images/5.jpg",
    nombre: "Festival 5K",
    fecha: "30 Nov. 2024",
    hora: "7:00 am",
    descripcion:
      "Únete a nuestra carrera para promover un estilo de vida saludable.",
    invitados: "Atleta G, Atleta H",
    costo: "25",
    lugar: "Miami",
  },
  {
    slug: "conferencia-innovacion",
    imagen: "/images/6.jpg",
    nombre: "Conferencia de Innovación",
    fecha: "5 Dic. 2024",
    hora: "9:00 am",
    descripcion: "Descubre las últimas tendencias y avances en tecnología.",
    invitados: "Ponente I, Ponente J",
    costo: "150",
    lugar: "Boston",
  },
];

export const members = [
    { name: "Emma Smith" },
    { name: "Liam Johnson" },
    { name: "Olivia Brown" },
    { name: "Noah Williams" },
    { name: "Ava Davis" },
    { name: "William Miller" },
    { name: "Sophia Wilson" },
    { name: "James Moore" },
    { name: "Isabella Taylor" },
    { name: "Benjamin Anderson" },
    { name: "Mia Martinez" },
    { name: "Jacob Garcia" },
    { name: "Charlotte Rodriguez" },
    { name: "Elijah Lopez" },
    { name: "Amelia Scott" },
  ];
  