import Button from "@/components/Button";
import Input from "@/components/Input";
import { Color, Container, Form, LinkStyled, Login } from "@/styles/Home.style";
import Head from "next/head";
import { useForm } from "react-hook-form";

export default function Home() {
  const {
    control,
    handleSubmit,
    formState: { errors, isDirty },
  } = useForm({
    defaultValues: {
      email: "",
      password: "",
    },
  });
  
  return (
    <>
      <Head>
        <title>Evenfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Container>
        <Login>
          <img src="/images/logo.png"/>
          <div>
            <h1>Bienvenido</h1>
            <p>Es bueno verte de nuevo! 👋</p>
            <p>Inicia sesión con tus datos aquí debajo 👇</p>
          </div>
          <Form>
            <Input fullWidth control={control} name="email" label="Correo"/>
            <Input fullWidth control={control} name="password" label="Contraseña"/>
            <Button text="Inicia sesión"/>
          </Form>
          <LinkStyled>
            <span>¿Aun no tienes una cuenta?</span>
            <a href="/register">Registrate aquí</a>
          </LinkStyled>
        </Login>
      </Container>
    </>
  );
}
